name: Continuous Integration

on:
  push:
    branches:
      - dev
      - ci

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:

      # TODO build wasm (outside of emulated chroot)
      # TODO chroot setup and dependency install can be cached
      # TODO tauri-cli can cached
      # TODO upload appimage and package artifacts separately when apk packages are supported

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/cache@v2
        with:
          path: /alpine
          key: alpine-chroot

      - uses: ./alpine-chroot-actions/install
        with:
          chroot_dir: /alpine
          arch: aarch64
          alpine_version: '0.13.0'
          mount: $PWD
          packages: build-base rust cargo nodejs-current npm webkit2gtk-dev libressl-dev squashfs-tools

      - uses: ./alpine-chroot-actions/exec
        with:
          cmd: |
            cargo install --version 1.0.0-beta.5 tauri-cli
            cd $PWD/tauri-example; cargo tauri build

      - run: tar -czf bundle.tar.gz tauri-example/src-tauri/target/release/bundle

      - uses: actions/upload-artifact@v2
        with:
          name: bundle.tar.gz
          path: bundle.tar.gz
