name: Continuous Integration

on:
  push:
    branches:
      - dev
      - ci

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:

      # TODO build wasm (outside of emulated chroot)
      # TODO chroot setup and dependency install can be cached
      # TODO tauri-cli can cached
      # TODO upload appimage and package artifacts separately when apk packages are supported

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - id: cache-chroot
        uses: actions/cache@v2
        with:
          path: /alpine
          key: alpine-chroot

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - if: steps.cache-chroot.outputs.cache-hit != 'true'
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: alpine-chroot-actions/node_modules
          key: actions_deps

      - if: |
          steps.cache-chroot.outputs.cache-hit != 'true'
          && steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          cd ./alpine-chroot-actions
          npm install

      - if: steps.cache-chroot.outputs.cache-hit != 'true'
        uses: ./alpine-chroot-actions/actions/install
        with:
          arch: aarch64
          packages: build-base rust cargo nodejs-current npm webkit2gtk-dev libressl-dev squashfs-tools

      - uses: ./alpine-chroot-actions/actions/exec
        with:
          cmd: cargo install --version 1.0.0-beta.5 tauri-cli

      - uses: ./alpine-chroot-actions/actions/exec
        with:
          cmd: cargo tauri build

      - run: tar -czf bundle.tar.gz tauri-example/src-tauri/target/release/bundle

      - uses: actions/upload-artifact@v2
        with:
          name: bundle.tar.gz
          path: bundle.tar.gz
