name: Continuous Integration

on:
  push:
    branches:
      - dev

jobs:

  build:
    name: build
    runs-on: ubuntu-20.04
    steps:

      - name: Install alpine-chroot-install
        run: |
          arch=aarch64
          wget https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.13.0/alpine-chroot-install
          sha1sum <(cat alpine-chroot-install) <(echo "44406f1a060b9f08b7e5ac264c8b9527b32fb54  alpine-chroot-install") || exit 1
          chmod +x alpine-chroot-install
          ln -s $PWD/alpine-chroot-install /usr/local/bin/alpine-chroot-install

      - name: Install chroot
        run: |
          mkdir /mnt/aarch64-alpine
          alpine-chroot-install -a aarch64 -d /aarch64-alpine -i /mnt/aarch64-alpine
          rm /alpine-chroot-install

      - name: Configure chroot
        run: |
          /aarch64-alpine/enter-chroot
          libs='webkit2gtk-dev libressl-dev'
          dev_tools='git squashfs-tools build-base rust cargo nodejs-current npm'
          apk add $libs $dev_tools
          useradd user
          
      - name: Build tauri-cli
        run: |
          /aarch64-alpine/enter-chroot -u user -c "cargo install --version 1.0.0-beta.5 tauri-cli"

      - name: Build app
        run: |
          /aarch64-alpine/enter-chroot -u user -c "cd tauri-example; cargo tauri build"
