name: Continuous Integration

on:
  push:
    branches:
      - dev
      - ci

jobs:
  build:
    name: build
    runs-on: ubuntu-20.04
    steps:

      # TODO build wasm (outside of emulated chroot)
      # TODO chroot setup and dependency install can be cached
      # TODO tauri-cli can cached
      # TODO upload appimage and package artifacts separately when apk packages are supported

      - uses: ./.github/alpine-chroot
        with:
          version: '0.13.0'
          arch: aarch64
          packages: webkit2gtk-dev libressl-dev squashfs-tools build-base rust cargo nodejs-current npm
          mount: $PWD

      - name: Build tauri-cli
        run: |
          /aarch64-alpine/enter-chroot -u user cargo install --version 1.0.0-beta.5 tauri-cli

      - uses: actions/checkout@v2

      - name: Build app
        run: |
          /aarch64-alpine/enter-chroot -u user cd $PWD/tauri-example; cargo tauri build

      - name: Move bundle to shared path
        run: |
          /aarch64-alpine/enter-chroot -u user mv tauri-example/src-tauri/target/release/bundle $PWD/mnt/aarch64-alpine/

      - name: Compress bundle
        run: |
          tar -czf bundle.tar.gz mnt/aarch64-alpine/bundle

      - uses: actions/upload-artifact@v2
        with:
          name: bundle.tar.gz
          path: bundle.tar.gz
